version: "3.8"

services:
  bd_lanchonete:
    container_name: bd_lanchonete
    build:
      context: .
      dockerfile: Dockerfile.bd
    env_file:
      - .env
    ports:
      ## host:container
      - "4050:3306"
    networks:
      - net_lanchonete
    volumes:
      - dados_lanchonete:/var/lib/mysql
    command: ["mysqld"]

  app:
    container_name: app_lanchonete
    build:
      context: .
      dockerfile: Dockerfile.app
    image: tech-challenge-1
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - net_lanchonete
    depends_on:
      - bd_lanchonete

volumes:
  dados_lanchonete:

networks:
  net_lanchonete:
    driver: bridge
